# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_auto_20171207_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureOrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='The client ID of the Azure AD application', max_length=255)),
                ('client_secret', models.CharField(help_text='The client key of the Azure AD application', max_length=255)),
                ('tenant', models.CharField(help_text='The Azure AD tenant domain where the Azure AD application resides', max_length=255)),
                ('rest_api_endpoint', models.URLField(help_text='The REST API endpoint of the Azure Media service account', max_length=255)),
                ('storage_account_name', models.CharField(help_text='Azure Blobs service storage account name', max_length=255)),
                ('storage_key', models.CharField(help_text='Azure Blobs service storage account key', max_length=255)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
    ]
